#!/bin/sh

# Run database migrations on current container before deploying new code
echo "Running database migrations..."
kamal app exec -d "$DESTINATION" 'bin/rails db:migrate'
echo "Database migrations complete (pre-deploy)"
